export const products = [
  {
    title: "Jacket North Bend",
    description: "Lorem ipsum dolor",
    imgSrc: "/media/products/camel.jpg",
    url: "/products/jacket-north-bend",
    id: "jacket-north-bend",
    artNr: "124-899-44",
    categoryId: "jackets",
    price: 499,
  },
  {
    title: "Dress Fiesta",
    description: "Lorem ipsum dolor",
    imgSrc: "/media/products/dresswhite.jpg",
    url: "/products/dress-fiesta",
    id: "dress-fiesta",
    artNr: "124-899-44",
    categoryId: "dress",
    price: 499,
  },
  {
    title: "Shoes Winter Women",
    description: "Lorem ipsum dolor",
    imgSrc: "/media/products/wintersko.jpg",
    url: "/products/shoes-winter-women",
    id: "shoes-winter-women",
    artNr: "124-899-44",
    categoryId: "shoes",
    price: 499,
  },
  {
    title: "Jacket Leather",
    description: "Lorem ipsum dolor",
    imgSrc: "/media/products/piele.jpg",
    url: "/products/jacket-leather",
    id: "jacket-leather",
    artNr: "124-899-44",
    categoryId: "jackets",
    price: 499,
  },
  {
    title: "Jack@Jones",
    description: "Lorem ipsum dolor",
    imgSrc: "/media/products/Productlarge.jpg",
    url: "/products/jack-jones",
    id: "jack-jones",
    artNr: "124-899-44",
    categoryId: "jeans",
    price: 499,
  },
  {
    title: "Blouses Only",
    description: "Lorem ipsum dolor",
    imgSrc: "/media/products/satinbluse.jpg",
    url: "/products/blouses-only",
    id: "blouses-only",
    artNr: "124-899-44",
    categoryId: "blouses",
    price: 499,
  },
  {
    title: "  Blouses Top",
    description: "Lorem ipsum dolor",
    imgSrc: "/media/products/redblus.jpg",
    url: "/products/blouses-top",
    id: "blouses-top",
    artNr: "124-899-44",
    categoryId: "blouses",
    price: 499,
  },
  {
    title: "Blouses white",
    description: "Lorem ipsum dolor",
    imgSrc: "/media/products/neck.jpg",
    url: "/products/blouses-white",
    id: "blouses-white",
    artNr: "124-899-44",
    categoryId: "blouses",
    price: 499,
  },
  {
    title: "Shoes summer",
    description: "Lorem ipsum dolor",
    imgSrc: "/media/products/shoes.jpg",
    url: "/products/shoes-summer",
    id: "shoes-summer",
    artNr: "124-899-44",
    categoryId: "shoes",
    price: 499,
  },
  {
    title: "Dress Desigual",
    description: "Lorem ipsum dolor",
    imgSrc: "/media/products/dress.jpg",
    url: "/products/dress-desigual",
    id: "dress-desigual",
    artNr: "124-899-44",
    categoryId: "dress",
    price: 499,
  },
  {
    title: "Jeans Brothers ",
    description: "Lorem ipsum dolor",
    imgSrc: "/media/products/jeans.jpg",
    url: "/products/jeans-brothers",
    id: "jeans-brothers",
    artNr: "124-899-44",
    categoryId: "jeans",
    price: 499,
  },
  {
    title: "Legging slim floral",
    description: "Lorem ipsum dolor",
    imgSrc: "/media/products/desigual.jpg",
    url: "/products/legging-slim-floral",
    id: "legging-slim-floral",
    artNr: "124-899-44",
    categoryId: "jeans",
    price: 499,
  },
];

export const categories = [
  {
    title: "Dress",
    imgSrc: "/media/categories/dress.jpg",
    id: "dress",
    url: "/categories/dress",
  },

  {
    title: "Shoes",
    imgSrc: "/media/categories/shoes.jpg",
    id: "shoes",
    url: "/categories/shoes",
  },

  {
    title: "Jeans",
    imgSrc: "/media/categories/jeans.jpg",
    id: "jeans",
    url: "/categories/jeans",
  },
  {
    title: "Jackets",
    imgSrc: "/media/categories/jacket.jpg",
    id: "jackets",
    url: "/categories/jackets",
  },
  {
    title: "Blouses",
    imgSrc: "/media/categories/redblus.jpg",
    id: "blouses",
    url: "/categories/blouses",
  },
];
